version: '3.8'
name: "roboton"
services:
  postgres:
    image: postgres:latest
    container_name: nuxt_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"